"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "./app-shell";

type Person = { displayName?: string; accountId?: string; avatarUrls?: Record<string, string> };
type Issue = { id: string; key: string; fields: { summary: string; status?: { name: string; statusCategory?: { colorName: string } }; priority?: { name: string }; assignee?: Person | null; reporter?: Person; updated?: string; created?: string; issuetype?: { name: string }; project?: { name: string; key: string }; description?: Adf; comment?: { comments: Comment[] } } };
type Comment = { id: string; body: Adf; author: Person; updateAuthor?: Person; created: string; updated: string };
type Adf = { version?: number; type?: string; text?: string; content?: Adf[]; attrs?: { url?: string } };
type IssueResponse = { issues: Issue[]; nextPageToken?: string; isLast?: boolean; errorMessages?: string[]; message?: string };

const adfText = (node?: Adf): string => {
  if (!node) return "";
  if (node.type === "hardBreak") return "\n";
  return `${node.text ?? ""}${node.content?.map(adfText).join("") ?? ""}`;
};
const toAdf = (text: string): Adf => ({ version: 1, type: "doc", content: text.split("\n").filter(Boolean).map((line) => ({ type: "paragraph", content: [{ type: "text", text: line }] })) });
const formatDate = (date?: string) => date ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(date)) : "–";

function Avatar({ person }: { person?: Person | null }) { const image = person?.avatarUrls?.["24x24"]; return image ? <img className="avatar" src={image} alt="" /> : <span className="avatar fallback">{person?.displayName?.slice(0, 1) ?? "–"}</span>; }

export function IssueWorkspace() {
  const [connected, setConnected] = useState<boolean | null>(null);
  const [siteName, setSiteName] = useState(""); const [configuredSiteUrl, setConfiguredSiteUrl] = useState(""); const [configuredProjectId, setConfiguredProjectId] = useState("");
  const [issues, setIssues] = useState<Issue[]>([]); const [nextPageToken, setNextPageToken] = useState<string>();
  const [loading, setLoading] = useState(false); const [moreLoading, setMoreLoading] = useState(false); const [error, setError] = useState("");
  const [jql, setJql] = useState(""); const [activeIssue, setActiveIssue] = useState<Issue | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [creating, setCreating] = useState(false);
  const checkStatus = useCallback(async () => { const response = await fetch("/api/auth/status"); const data = await response.json(); setConnected(data.connected); setSiteName(data.siteName ?? ""); }, []);
  const loadIssues = useCallback(async (token?: string, append = false, query?: string) => {
    if (!append) setLoading(true); else setMoreLoading(true); setError("");
    try { const params = new URLSearchParams({ limit: "20", ...(query ? { jql: query } : {}), ...(token ? { nextPageToken: token } : {}) }); const response = await fetch(`/api/issues?${params}`); const data = await response.json() as IssueResponse; if (!response.ok) throw new Error(data.message || data.errorMessages?.[0] || "티켓을 불러오지 못했습니다."); setIssues((previous) => append ? [...previous, ...data.issues] : data.issues); setNextPageToken(data.isLast ? undefined : data.nextPageToken); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "알 수 없는 오류가 발생했습니다."); } finally { setLoading(false); setMoreLoading(false); }
  }, []);
  useEffect(() => { const connection = localStorage.getItem("jira-connect:connection"); if (connection) { try { const saved = JSON.parse(connection); setConfiguredSiteUrl(saved.siteUrl ?? ""); setConfiguredProjectId(saved.projectId ?? ""); } catch { setConfiguredSiteUrl(""); setConfiguredProjectId(""); } } void checkStatus(); }, [checkStatus]);
  useEffect(() => { if (connected && configuredProjectId) void loadIssues(); }, [connected, configuredProjectId, loadIssues]);
  async function openIssue(issue: Issue) { setActiveIssue(issue); setDetailLoading(true); try { const response = await fetch(`/api/issues/${issue.key}`); const data = await response.json(); if (!response.ok) throw new Error(data.message || "상세 정보를 가져오지 못했습니다."); setActiveIssue(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "상세 정보를 가져오지 못했습니다."); } finally { setDetailLoading(false); } }
  function search(event: FormEvent) { event.preventDefault(); void loadIssues(undefined, false, jql || undefined); }
  return <AppShell><section className="page-head issue-head"><div><p className="eyebrow">Jira 업무</p><h1>티켓 목록</h1><p>{connected ? `${siteName}의 지정한 프로젝트 티켓을 최신순으로 확인합니다.` : "티켓을 불러오려면 Jira 계정을 연결해 주세요."}</p></div>{connected && <div className="connection-chip"><span className="status-dot" />{configuredProjectId ? `프로젝트 ID ${configuredProjectId}` : "프로젝트 설정 필요"}</div>}</section>
    {!connected && <LoginPanel siteUrl={configuredSiteUrl} error={new URLSearchParams(typeof window !== "undefined" ? window.location.search : "").get("error")} />}
    {connected && !configuredProjectId && <ProjectRequiredPanel />}
    {connected && configuredProjectId && <><div className="toolbar"><form className="search-row" onSubmit={search}><input aria-label="JQL 검색" value={jql} onChange={(event) => setJql(event.target.value)} placeholder="추가 JQL 조건을 입력하세요. 예: status != Done" /><button className="button primary" type="submit">조회</button><button className="button ghost" type="button" onClick={() => { setJql(""); void loadIssues(); }}>초기화</button></form><button className="button primary" type="button" onClick={() => setCreating(true)}>+ 티켓 만들기</button></div>
      {error && <div className="alert error"><span>!</span>{error}</div>}
      <section className="ticket-card"><div className="list-caption"><span>총 {issues.length}건 표시</span><span>Jira와 실시간 연동</span></div>{loading ? <LoadingRows /> : issues.length ? <div className="issue-list">{issues.map((issue) => <button className="issue-row" key={issue.id} onClick={() => void openIssue(issue)}><span className="issue-key">{issue.key}</span><span className="issue-summary"><strong>{issue.fields.summary}</strong><small>{issue.fields.project?.name} · {issue.fields.issuetype?.name}</small></span><span className="issue-status">{issue.fields.status?.name ?? "상태 없음"}</span><span className="assignee"><Avatar person={issue.fields.assignee} />{issue.fields.assignee?.displayName ?? "담당자 없음"}</span><time>{formatDate(issue.fields.updated)}</time></button>)}</div> : <div className="empty-state"><strong>표시할 티켓이 없습니다.</strong><p>검색 조건을 바꾸거나 Jira에서 티켓 접근 권한을 확인해 주세요.</p></div>}{nextPageToken && <div className="load-more"><button className="button secondary" disabled={moreLoading} onClick={() => void loadIssues(nextPageToken, true, jql || undefined)}>{moreLoading ? "불러오는 중…" : "다음 페이지 불러오기"}</button></div>}</section>
      {activeIssue && <IssueDrawer issue={activeIssue} loading={detailLoading} onClose={() => setActiveIssue(null)} onRefresh={() => void openIssue(activeIssue)} />}{creating && <CreateIssueDialog projectId={configuredProjectId} onClose={() => setCreating(false)} onCreated={(issue) => { setCreating(false); void loadIssues(); void openIssue(issue); }} />}</>}
  </AppShell>;
}

function LoginPanel({ error, siteUrl }: { error: string | null; siteUrl: string }) { const message = error === "oauth_config" ? "OAuth 환경 변수가 설정되지 않았습니다. .env.example을 확인해 주세요." : error === "site_not_authorized" ? "저장한 Jira 사이트에 대한 접근 권한이 없습니다. 연계 관리의 사이트 주소와 로그인 계정을 확인해 주세요." : error === "site_required" ? "Jira 연계 관리에서 사이트 주소를 먼저 저장해 주세요." : error ? "Jira 로그인에 실패했습니다. 권한과 설정을 확인한 뒤 다시 시도해 주세요." : null; return <section className="login-panel card"><span className="brand-mark large">J</span><h2>Jira 계정을 연결해 주세요</h2><p>연계 관리에서 저장한 Jira 사이트에 한해, 개인별 OAuth 권한으로 티켓을 불러옵니다.</p>{message && <div className="alert error"><span>!</span>{message}</div>}{siteUrl ? <a href={`/api/auth/login?siteUrl=${encodeURIComponent(siteUrl)}`} className="button primary">설정한 Jira 사이트로 계속하기</a> : <a href="/integration" className="button primary">Jira 연계 관리로 이동</a>}<small>{siteUrl ? `${siteUrl}에 연결합니다.` : "연결할 Jira 사이트 주소를 먼저 저장해 주세요."}</small></section>; }
function ProjectRequiredPanel() { return <section className="login-panel card"><span className="brand-mark large">!</span><h2>프로젝트 설정이 필요합니다</h2><p>티켓 목록을 보기 전에 Jira 연계 관리에서 프로젝트 ID 또는 키를 저장해 주세요.</p><a href="/integration" className="button primary">Jira 연계 관리로 이동</a></section>; }
function LoadingRows() { return <div className="loading-rows">{Array.from({ length: 6 }, (_, index) => <div className="loading-row" key={index}><span /><span /><span /></div>)}</div>; }

function CreateIssueDialog({ projectId, onClose, onCreated }: { projectId: string; onClose: () => void; onCreated: (issue: Issue) => void }) {
  const [issueType, setIssueType] = useState("Task"); const [summary, setSummary] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function createIssue(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/issues", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ issueType, summary, ...(description.trim() ? { description: toAdf(description) } : {}) }) }); const data = await response.json() as { key?: string; id?: string; message?: string; errorMessages?: string[]; errors?: Record<string, string> }; if (!response.ok || !data.key || !data.id) throw new Error(data.message || data.errorMessages?.[0] || Object.values(data.errors ?? {})[0] || "티켓을 생성하지 못했습니다."); onCreated({ id: data.id, key: data.key, fields: { summary, project: { key: projectId, name: projectId }, issuetype: { name: issueType } } }); } catch (caught) { setError(caught instanceof Error ? caught.message : "티켓을 생성하지 못했습니다."); } finally { setSaving(false); } }
  return <div className="drawer-backdrop" role="dialog" aria-modal="true" aria-label="새 티켓 만들기"><section className="create-dialog card"><header className="dialog-header"><div><p className="eyebrow">새 티켓</p><h2>Jira 티켓 만들기</h2><p>프로젝트 ID {projectId}에 새 업무를 등록합니다.</p></div><button className="icon-button" aria-label="티켓 만들기 닫기" type="button" onClick={onClose}>×</button></header><form className="create-form" onSubmit={createIssue}><label>이슈 유형<input value={issueType} onChange={(event) => setIssueType(event.target.value)} placeholder="예: Task, Bug, Story" required autoFocus /></label><label>요약<input value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="업무 내용을 한 줄로 입력하세요" required /></label><label>설명<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="배경, 작업 범위, 완료 기준 등을 입력하세요" rows={7} /></label>{error && <div className="alert error"><span>!</span>{error}</div>}<footer className="dialog-actions"><button className="button ghost" type="button" onClick={onClose}>취소</button><button className="button primary" disabled={saving}>{saving ? "Jira에 등록 중…" : "Jira 티켓 만들기"}</button></footer></form></section></div>;
}

function IssueDrawer({ issue, loading, onClose, onRefresh }: { issue: Issue; loading: boolean; onClose: () => void; onRefresh: () => void }) {
  const [editing, setEditing] = useState(false); const [summary, setSummary] = useState(issue.fields.summary); const [description, setDescription] = useState(adfText(issue.fields.description)); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [comment, setComment] = useState(""); const [commentLoading, setCommentLoading] = useState(false); const [editCommentId, setEditCommentId] = useState<string>(); const [editCommentText, setEditCommentText] = useState("");
  const comments = issue.fields.comment?.comments ?? [];
  async function saveIssue(event: FormEvent) { event.preventDefault(); setSaving(true); setNotice(""); try { const response = await fetch(`/api/issues/${issue.key}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fields: { summary, description: toAdf(description) } }) }); if (!response.ok) { const data = await response.json(); throw new Error(data.message || "티켓을 저장하지 못했습니다."); } setEditing(false); setNotice("티켓이 Jira에 저장되었습니다."); onRefresh(); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "저장하지 못했습니다."); } finally { setSaving(false); } }
  async function addComment(event: FormEvent) { event.preventDefault(); if (!comment.trim()) return; setCommentLoading(true); try { const response = await fetch(`/api/issues/${issue.key}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: toAdf(comment) }) }); if (!response.ok) throw new Error(); setComment(""); onRefresh(); } catch { setNotice("댓글을 등록하지 못했습니다."); } finally { setCommentLoading(false); } }
  async function updateComment(id: string) { if (!editCommentText.trim()) return; const response = await fetch(`/api/issues/${issue.key}/comments/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: toAdf(editCommentText) }) }); if (response.ok) { setEditCommentId(undefined); onRefresh(); } else setNotice("댓글을 수정하지 못했습니다."); }
  async function deleteComment(id: string) { if (!window.confirm("이 댓글을 삭제할까요? Jira에서도 즉시 삭제됩니다.")) return; const response = await fetch(`/api/issues/${issue.key}/comments/${id}`, { method: "DELETE" }); if (response.ok) onRefresh(); else setNotice("댓글을 삭제하지 못했습니다."); }
  return <div className="drawer-backdrop" role="dialog" aria-modal="true" aria-label={`${issue.key} 상세`}><aside className="issue-drawer"><header className="drawer-header"><div><span className="issue-key">{issue.key}</span><h2>{issue.fields.summary}</h2></div><button className="icon-button" aria-label="상세 닫기" onClick={onClose}>×</button></header>{loading ? <div className="drawer-loading">Jira 상세 정보를 불러오는 중…</div> : <div className="drawer-content"><div className="drawer-actions"><button className="button secondary" onClick={() => setEditing((value) => !value)}>{editing ? "편집 취소" : "티켓 수정"}</button></div>{notice && <div className={`alert ${notice.includes("저장되었습니다") ? "success" : "error"}`}><span>!</span>{notice}</div>}{editing ? <form className="edit-form" onSubmit={saveIssue}><label>요약<input value={summary} onChange={(event) => setSummary(event.target.value)} required /></label><label>설명<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="티켓 설명을 입력하세요" rows={7} /></label><button className="button primary" disabled={saving}>{saving ? "저장 중…" : "Jira에 변경사항 저장"}</button></form> : <><section className="detail-section"><h3>설명</h3><p className="preserve-lines">{adfText(issue.fields.description) || "등록된 설명이 없습니다."}</p></section><section className="detail-meta"><Meta label="상태" value={issue.fields.status?.name ?? "–"} /><Meta label="담당자" value={issue.fields.assignee?.displayName ?? "미지정"} /><Meta label="우선순위" value={issue.fields.priority?.name ?? "–"} /><Meta label="업데이트" value={formatDate(issue.fields.updated)} /></section></>}
    <section className="comments"><div className="section-title"><h3>댓글</h3><span>{comments.length}</span></div><form className="comment-form" onSubmit={addComment}><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Jira에 공유할 댓글을 작성하세요" rows={3} /><button className="button primary" disabled={commentLoading}>{commentLoading ? "등록 중…" : "댓글 등록"}</button></form><div className="comment-list">{comments.map((item) => <article className="comment" key={item.id}><div className="comment-author"><Avatar person={item.author} /><strong>{item.author.displayName ?? "Jira 사용자"}</strong><time>{formatDate(item.updated || item.created)}</time></div>{editCommentId === item.id ? <div className="inline-edit"><textarea value={editCommentText} onChange={(event) => setEditCommentText(event.target.value)} rows={3} /><div><button className="text-button" type="button" onClick={() => void updateComment(item.id)}>저장</button><button className="text-button" type="button" onClick={() => setEditCommentId(undefined)}>취소</button></div></div> : <><p className="preserve-lines">{adfText(item.body)}</p><div className="comment-actions"><button className="text-button" onClick={() => { setEditCommentId(item.id); setEditCommentText(adfText(item.body)); }}>수정</button><button className="text-button danger" onClick={() => void deleteComment(item.id)}>삭제</button></div></>}</article>)}</div></section></div>}</aside></div>;
}
function Meta({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
